title: 吴建峰的个人主页
author: Jianfeng Wu
email: 1009346982@qq.com
copyright: © 2021 GitHub User
description: > # this means to ignore newlines until "show_excerpts:"
  Currently studying at Nankai University.

show_excerpts: false # set to true to show excerpts on the homepage

lin:
  date_format: "%b %-d, %Y"

  # path to the author avatar image
  avatar_path: assets/images/wujianfeng.jpg

  # generate social links
  social_links:
    github: Pisces-29
    facebook: jekyll
    instagram: nyankosensi33

theme: lin

plugins:
 - jekyll-feed
 - jekyll-seo-tag
